### ISSUE TITLE
Level 1 swath?

### ISSUE THREAD

**Issue by timjnightingale** [Unidata/EC-netCDF-CF#4]
There is one other swath type I can think of - the natural measurement frame of scanning instruments, which build up a raster whose geometry is dependent on the design of the scanning optics. Data collection is usually (but not always) regular in time around each scan, but not necessarily in scan angle (scan mechanisms tend to "jitter" a little) or in anything else.

This might be particularly useful for satellite instruments such as SLSTR and AATSR where the measurement frame is very distorted compared to a quasi-Cartesian image grid, but is relevant for pretty much any scanning instrument, as none collect data directly onto a regular swath. Think of this as a "Level 1" swath!

I think the data description might look something like:

dimensions:
  scan = UNLIMITED ;   // along track scan index
  pixel = 512 ;        // around scan pixel index

variables:
  float lat(scan, pixel) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(scan, pixel) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(scan, pixel) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(scan, pixel) ;
    swath_data:featureType = “???” ;
    swath_data:coordinates = "lon lat" ;

This is always the most efficient way to store native data from scanning instruments. Is there a place for a description like this?

Regards,

Tim Nightingale

RAL Space
STFC Rutherford Appleton Laboratory
Harwell Campus
Didcot
Oxon OX11 0QX
UK

**Comment by ghost** [comment]
The [Swath](https://github.com/Unidata/EC-netCDF-CF/blob/499949bba047210c06dfbaa25a9d336e3be485ba/swath/swath.adoc#swath) feature type corresponds to your data description, specifically Example 13.

Although the `time` coordinate in the Swath examples is one-dimensional the section on [time coordinates](https://github.com/Unidata/EC-netCDF-CF/blob/499949bba047210c06dfbaa25a9d336e3be485ba/swath/swath.adoc#time-coordinates) permits multidimensional coordinates as well.

The `swath_data` in your data description would then look like:

```c++
  float swath_data(scan, pixel) ;
    swath_data:featureType = "swath" ;
    swath_data:coordinates = "time lon lat" ;
```

**Comment by ghost** [comment]
@timjnightingale Do you have any follow-on comments or questions about this issue? If not, can you please close it?
